version: '3.0'

services:
  ubuntu-xfce:
    image: accetto/ubuntu-vnc-xfce
    restart: always
    # vnc server default listen at port 5901 with password "headless"
    ports:
      - 5901/tcp
  guacd:
    image: guacamole/guacd:1.5.3
    restart: always
  postgres:
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_PASSWORD: 'passw0rd'
      POSTGRES_USER: guacamole_user
    image: postgres:15.2-alpine
    restart: always
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./data:/var/lib/postgresql/data
  guacamole:
    depends_on:
      - guacd
      - postgres
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRESQL_DATABASE: guacamole_db
      POSTGRESQL_HOSTNAME: postgres
      POSTGRESQL_PASSWORD: 'passw0rd'
      POSTGRESQL_USER: guacamole_user
      # reference https://guacamole.apache.org/doc/1.5.0/gug/guacamole-docker.html#custom-extensions-and-guacamole-home
      GUACAMOLE_HOME: /tmp/guacamole_home_template
    image: guacamole/guacamole:1.5.3
    volumes:
      # mount guacamole jwt auth plugin
      # reference https://guacamole.apache.org/doc/1.5.0/gug/guacamole-docker.html#custom-extensions-and-guacamole-home
      - ./guacamole:/tmp/guacamole_home_template
      - ../gradle/build/guacamole-auth-jwt.jar:/etc/guacamole/extensions/
    links:
      - guacd
    ports:
      - "8081:8080"
    restart: always
  nginx:
    depends_on:
      - guacamole
      - postgres
    volumes:
      - ./frontend/build:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    image: nginx
    links:
      - guacamole
    ports:
      - "8080:80"
    restart: always
